### ISSUE TITLE
error when trying to pre register a domain

### ISSUE THREAD

**Issue by jdetychey** [nebulis-io/website#2]
I filled the form like this:

name
Jerome de Tychey
email
jdetychey@gmail.com
Cluster
home
Domain
asseth

the popup ''Do you want to pre-register home.asseth?'' appears and the page loads this error message:
 Oh snap! Something went wrong with your address reservation. Check your details and try again.

**Comment by Physes** [comment]
Confirmed: I tried this and got the same. We're going to prepare a few updates to the registration process.

**Comment by harshjv** [comment]
With the same information, it says this to me;

<img width="1280" alt="screen shot 2016-11-13 at 6 32 07 pm" src="https://cloud.githubusercontent.com/assets/2311316/20245833/82d6aab8-a9cf-11e6-9db5-afe7b9b0da89.png">

**Comment by Physes** [comment]
I think I know what went wrong- I tried to sign up with "subscribe" ticked, and it didn't work. However when subscribe was unticked it worked. Could there be something wrong with the mailchimp signup process?

**Comment by harshjv** [comment]
@Physes correct! Let me hide subscription for now. Will enable it after a fix.

**Comment by harshjv** [comment]
Closing in favor of 80b0b7f59355bbaa835ea036b1980e16d0f05d30
