### ISSUE TITLE
Choose website address: www or non-www

### ISSUE THREAD

**Issue by harshjv** [nebulis-io/website#3]
What version do we want to keep? www.nebulis.io or just nebulis.io

Also, only https version of the website will work. Non-https will be redirected to https version.

This way, we will have good search engine visibility.

**Comment by Physes** [comment]
I think we should enable both, and also redirect any "http" queries to the https version.

**Comment by harshjv** [comment]
Ya, we will have both versions enabled. But we have to choose a primary address. The other address will 301 redirect to this primary address for SEO.

For example, facebook.com redirects to www.facebook.com, but www.twitter.com redirects to twitter.com
